adds mongoose
z9877969/node-js pull request #3
Opened 2023-05-09 23:51 UTC by z9877969

2023-05-11 10:20 UTC, NadyaHristuk requested changes
Із критичного сервіси винести з хелперів. Або щоб все буело через сервіси, або нічого. 
Із бажаного - перевірку від джої винести в міделвару. 
- контроллери відокремити від роутві і теж винести в окрему папку з контроллерами.

2023-05-11 10:20 UTC, NadyaHristuk commented on routes/api/contacts.js
>  const contactSchema = Joi.object({
це в міделвари краще виносити ))

2023-05-11 10:20 UTC, NadyaHristuk commented on routes/api/contacts.js
> +    const { error } = updatingNameSchema.validate(body);
судячи з роута, збираєшся оновлювати значення в полі фаворіт, а виходічи з назви схеми, збираєшся оновлювати ім'я. Креще давати відповідні назви

2023-05-11 10:20 UTC, NadyaHristuk commented on routes/api/contacts.js
> +    if (!body || error) {
це теж краще описувати через мін 1, і не додавати сюди перевірку на !body

2023-05-11 10:20 UTC, NadyaHristuk commented on helpers/updateStatusContact.js
> +const Contact = require("../models/contact");
ну це не хелпер. це сервіси. А хелпери, то те, що ти будеш багато разів в різних місцях викликати. А сервіси, це зверненя до бази данних. 
друге. Чому тоді один сервіс винесен, як сервіс, а все інші функції зверення до бази ти залишив в роутах? або всі виносити в сервіси, або ні одного.

2023-05-11 10:20 UTC, NadyaHristuk commented on routes/api/contacts.js
>  router.get("/", async (req, res, next) => {
Контроллери на 3 дз вже базано виносити з роутів, і записиувати окремо, а тут тільки викликами функцію потрібного контроллера.

2023-05-17 23:04 UTC, z9877969 commented on helpers/updateStatusContact.js
> +const Contact = require("../models/contact");
так було сказано зробити в ДЗ.

2023-05-17 23:06 UTC, z9877969 commented on routes/api/contacts.js
> +    if (!body || error) {
це не займав, побачив тільки після того як відправив пул реквест. потім розберусь і з цим питанням.

2023-05-18 16:58 UTC, NadyaHristuk approved these changes
Так, тепер вірно

2023-05-18 16:58 UTC, merged